if (!window.__gtaBuild21Turns) {
window.__gtaBuild21Turns = true;

const PERFECT_LINE21={id:'perfect_line',title:'PERFECT LINE',type:'multi_bonus_run',spawn:{x:4550,y:-650},time:100,reward:7500,signalBonus:2000,damageBonus:3000,color:'#ef61c5',checkpoints:[[5000,0],[5000,650],[4100,1200],[3200,650]],radius:95,maxCheckpointSpeed:118,heat:1};
if(!CAMPAIGN.some(m=>m.id==='perfect_line'))CAMPAIGN.push(PERFECT_LINE21);
let perfectSignal21=true,perfectDamage21=true,perfectStartHp21=0;

function prepareTurnPockets21(){for(const c of cars){if(!c||!c.ai||c.destroyed)continue;if(typeof ensureLane20==='function')ensureLane20(c);const r=c.laneBase20;if(!r||r.length<3)continue;const i=((c.index||0)%r.length+r.length)%r.length,turn=r[i],next=r[(i+1)%r.length];const dx=turn[0]-c.x,dy=turn[1]-c.y,d=Math.hypot(dx,dy);if(d>190){c.turnPocket21=false;continue;}const fx=Math.sin(c.rot),fy=-Math.cos(c.rot),ox=next[0]-turn[0],oy=next[1]-turn[1],m=Math.hypot(ox,oy)||1,cross=fx*(oy/m)-fy*(ox/m),dot=fx*(ox/m)+fy*(oy/m);if(dot>.82){c.turnPocket21=false;continue;}c.laneTarget20=cross>0?1:-1;c.turnPocket21=true;}}
function lineBlocked21(a,b){for(let i=1;i<10;i++){const t=i/10,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;for(const q of buildings)if(x>q.x-18&&x<q.x+q.w+18&&y>q.y-18&&y<q.y+q.h+18)return true;}return false;}
function nearestAxis21(v,list){let best=list[0]||v,d=Infinity;for(const n of list){const q=Math.abs(n-v);if(q<d){d=q;best=n;}}return best;}
function routePolice21(dt){const target=playerTarget();if(!target)return;for(const p of police){if(!p)continue;if(wanted>=3&&dist(p,target)<260){p._route21=null;continue;}if(!lineBlocked21(p,target)){p._route21=null;continue;}const px=nearestAxis21(p.x,ROAD_X),py=nearestAxis21(p.y,ROAD_Y),tx=nearestAxis21(target.x,ROAD_X),ty=nearestAxis21(target.y,ROAD_Y),a={x:tx,y:py},b={x:px,y:ty};p._route21=dist(p,a)<dist(p,b)?a:b;const w=p._route21,desired=Math.atan2(w.y-p.y,w.x-p.x)+Math.PI/2,e=wrap(desired-p.rot);p.rot+=clamp(e,-1.4*dt,1.4*dt);}}
function perfectDamageState21(){if(!missionCar||missionCar.destroyed)return false;return Number(missionCar.hp||0)>=perfectStartHp21;}
try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const s=JSON.parse(raw);if(levelComplete&&Number(s.campaignIndex)===10)campaignIndex=10;}}catch(e){console.warn('Build 21 saved mission restore failed',e);}

const startMission21Base=startMission;
startMission=function(){const m=mission();if(m.id!=='perfect_line')return startMission21Base();missionTimer=m.time||0;chainIndex=0;chainPoints=m.checkpoints||[];perfectSignal21=true;perfectDamage21=true;missionState='chain_steal';spawnMissionCar(m);perfectStartHp21=Number(missionCar&&missionCar.hp||0);statusMessage='PERFECT LINE — STEAL THE PINK COURIER';statusTimer=2.4;if(typeof sfxAccept14==='function')sfxAccept14();if(typeof banner15==='function')banner15('PERFECT LINE','2 BONUSES ACTIVE');};
const completeMission21Base=completeMission;
completeMission=function(){const m=mission();if(m.id!=='perfect_line')return completeMission21Base();const sb=perfectSignal21?(m.signalBonus||2000):0,db=perfectDamage21?(m.damageBonus||3000):0,reward=(m.reward+sb+db)*multiplier,summary=`${perfectSignal21?'SIGNAL ✓':'SIGNAL ×'} · ${perfectDamage21?'DAMAGE ✓':'DAMAGE ×'}`;score+=reward;multiplier=Math.min(multiplier+1,5);missionCar=null;missionTimer=0;chainIndex=0;chainPoints=[];campaignIndex=0;missionState='cooldown';missionCooldown=3;statusMessage=`PERFECT LINE COMPLETE — ${summary} +${reward}`;statusTimer=3.6;perfectSignal21=true;perfectDamage21=true;perfectStartHp21=0;saveProgress();if(typeof sfxMission14==='function')sfxMission14();if(typeof banner15==='function')banner15('PERFECT LINE',summary);};
const failMission21Base=failMission;
failMission=function(msg){perfectSignal21=true;perfectDamage21=true;perfectStartHp21=0;return failMission21Base(msg);};
const missionText21Base=missionText;
missionText=function(){if(mission().id==='perfect_line'){const time=` · TIME ${String(Math.ceil(missionTimer)).padStart(2,'0')}`,flags=`SIGNAL ${perfectSignal21?'✓':'×'} · DAMAGE ${perfectDamage21?'✓':'×'}`;if(missionState==='chain_steal')return `STEAL THE PINK COURIER · ${flags}${time}`;if(missionState==='chain_drive')return `PERFECT STOP ${Math.min(chainIndex+1,chainPoints.length)}/${chainPoints.length} · ${flags}${time}`;}return missionText21Base();};
const showUnlock21Base=showUnlock;
showUnlock=function(){showUnlock21Base();const el=document.getElementById('build9-unlock');if(el)el.innerHTML=el.innerHTML.replace('7 POST-CLEAR JOBS UNLOCKED','8 POST-CLEAR JOBS UNLOCKED').replace('HARBOR EAST + 7 POST-CLEAR JOBS UNLOCKED','HARBOR EAST + 8 POST-CLEAR JOBS UNLOCKED');};
const openMissionMenu21Base=openMissionMenu;
openMissionMenu=function(){openMissionMenu21Base();const menu=document.getElementById('build11-missions');if(!menu)return;menu.innerHTML=menu.innerHTML.replace(/BUILD (11|12|13|14|15|16|17|18|19|20)/g,'BUILD 21').replace('Keys 1–9, 0 select','Keys 1–9, 0, - select');const b=menu.querySelector('[data-mission="10"]');if(b){const ok=!b.disabled;b.innerHTML=`<b>11. PERFECT LINE</b><span style="float:right">${ok?'SELECT':'LOCKED'}</span><br><span style="font-size:11px;font-weight:500;opacity:.72">2 independent bonuses · signal +2000 · no damage +3000</span>`;}menu.querySelectorAll('[data-mission]').forEach(x=>{const c=x.cloneNode(true);x.replaceWith(c);c.addEventListener('click',()=>selectMission(Number(c.dataset.mission)));});};
addEventListener('keydown',e=>{if(missionMenuOpen&&e.code==='Minus'&&!e.repeat){e.preventDefault();selectMission(10);}});

const draw21Base=draw;
draw=function(){draw21Base();const pt=playerTarget();ctx.save();ctx.translate(W/2,H/2);ctx.scale(camera.zoom,camera.zoom);ctx.translate(-camera.x,-camera.y);ctx.strokeStyle='rgba(238,224,120,.30)';ctx.lineWidth=2;for(const x of ROAD_X)for(const y of ROAD_Y){if(pt&&Math.hypot(x-pt.x,y-pt.y)>850)continue;ctx.beginPath();ctx.moveTo(x-78,y-34);ctx.lineTo(x-30,y-34);ctx.lineTo(x-20,y-44);ctx.stroke();ctx.beginPath();ctx.moveTo(x+34,y-78);ctx.lineTo(x+34,y-30);ctx.lineTo(x+44,y-20);ctx.stroke();}ctx.restore();};
const update21Base=update;
update=function(dt){prepareTurnPockets21();update21Base(dt);routePolice21(dt);if(mission().id==='perfect_line'&&missionState==='chain_drive'&&inVehicle&&currentCar===missionCar){if(perfectSignal21&&typeof redViolation20==='function'&&redViolation20(missionCar)){perfectSignal21=false;statusMessage='SIGNAL BONUS LOST — RED LIGHT';statusTimer=2;if(typeof banner15==='function')banner15('BONUS LOST','SIGNAL DISCIPLINE');}if(perfectDamage21&&!perfectDamageState21()){perfectDamage21=false;statusMessage='DAMAGE BONUS LOST — COURIER HIT';statusTimer=2;if(typeof banner15==='function')banner15('BONUS LOST','UNTOUCHED COURIER');}}const bar=document.getElementById('build14-drive');if(bar){bar.textContent=bar.textContent.replace('BUILD 20','BUILD 21');if(!bar.textContent.includes('TURN POCKETS'))bar.textContent+=' · TURN POCKETS';}};
const front21=document.getElementById('build11-front');if(front21){front21.innerHTML=front21.innerHTML.replace(/BUILD 20/g,'BUILD 21').replace('Lane intelligence + bonus jobs online','Turn pockets + routed pursuit online');const bold=front21.querySelectorAll('b');if(bold.length>1)bold[1].textContent=`${unlockedMissionCount()}/${CAMPAIGN.length}`;}
if(typeof banner15==='function')banner15('TURN POCKETS ONLINE','BUILD 21');
}
